BRM_HOST: "192.168.209.108"
BRM_USER: "rmsuser"
BRM_PWD: "c1g2b3u4"
SOAP_BASE_URL:  "http://192.168.209.159:7779/"
SOAP_CHNL_URL:  "infranetwebsvc/BRMBaseService"
OEP_SOAP_BASE_URL:  "http://192.168.209.159:7779/"
OEP_SOAP_CHNL_URL:  "OrderEntryWebservice-1.0/orderentry"
TEST: "/opt/code_root/rmsuser/opt/portal/7.5/sys/test"
USAGE: "C:\\robot_20112023\\robot_billing_code_18Mar2024\\ExternalBin\\seagull"
PVT: "032105002024"
FLAG: "YES"
GUI_URL: "https://test.bluerise.solutions/"